# Generated by Django 4.0 on 2021-12-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('categoria', models.CharField(choices=[('Dog', 'Cachorro'), ('Cat', 'Gato'), ('Bunny', 'Coelho')], max_length=10)),
                ('cor', models.CharField(choices=[('Black', 'Preto'), ('White', 'Branco'), ('Gray', 'Cinz'), ('Brown', 'Marrom')], max_length=10)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
