# Generated by Django 4.0 on 2021-12-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consultapet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cargo', models.CharField(choices=[(1, 'Veterinário'), (2, 'Financeiro'), (3, 'Atendimento')], max_length=10)),
            ],
        ),
    ]
