# Generated by Django 4.0 on 2021-12-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('1', 'Veterinário'), ('2', 'Financeiro'), ('3', 'Atendimento')], max_length=10),
        ),
    ]
